AWSTemplateFormatVersion: "2010-09-09"
Description: A template to create a VPC with structured subnets and associated infrastructure.

Parameters:
  Environment:
    Type: String
    Description: Environment name
    Default: dev
  VpcCIDR:
    Type: String
    Description: VPC CIDR block
    Default: 10.226.232.0/23
  ACIT_Web_Subnet1CIDR:
    Type: String
    Description: CIDR block for ACIT_Web_Subnet1
    Default: 10.226.232.0/25
  ACIT_Web_Subnet2CIDR:
    Type: String
    Description: CIDR block for ACIT_Web_Subnet2
    Default: 10.226.232.128/25
  ACIT_APP_Subnet1CIDR:
    Type: String
    Description: CIDR block for ACIT_APP_Subnet1
    Default: 10.226.233.0/25
  ACIT_APP_Subnet2CIDR:
    Type: String
    Description: CIDR block for ACIT_APP_Subnet2
    Default: 10.226.233.128/25
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair name for EC2 instance
  RestrictedIP:
    Type: String
    Description: Restricted IP for SSH access
    Default: 100.16.251.45/32

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-VPC
        - Key: Environment
          Value: !Ref Environment

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-IGW
        - Key: Environment
          Value: !Ref Environment

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  ACITWebSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ACIT_Web_Subnet1CIDR
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ACIT_Web_Subnet1
        - Key: Environment
          Value: !Ref Environment

  ACITWebSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ACIT_Web_Subnet2CIDR
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ACIT_Web_Subnet2
        - Key: Environment
          Value: !Ref Environment

  ACITAppSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ACIT_APP_Subnet1CIDR
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ACIT_APP_Subnet1
        - Key: Environment
          Value: !Ref Environment

  ACITAppSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ACIT_APP_Subnet2CIDR
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ACIT_APP_Subnet2
        - Key: Environment
          Value: !Ref Environment

  NATIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway1:
    Type: AWS::EC2::NatGateway
    DependsOn: AttachGateway
    Properties:
      AllocationId: !GetAtt NATIP1.AllocationId
      SubnetId: !Ref ACITWebSubnet1

  NATIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway2:
    Type: AWS::EC2::NatGateway
    DependsOn: AttachGateway
    Properties:
      AllocationId: !GetAtt NATIP2.AllocationId
      SubnetId: !Ref ACITWebSubnet2

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-PublicRouteTable
        - Key: Environment
          Value: !Ref Environment

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ACITWebSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ACITWebSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-PrivateRouteTable1
        - Key: Environment
          Value: !Ref Environment

  PrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway1

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ACITAppSubnet1
      RouteTableId: !Ref PrivateRouteTable1

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-PrivateRouteTable2
        - Key: Environment
          Value: !Ref Environment

  PrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway2

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ACITAppSubnet2
      RouteTableId: !Ref PrivateRouteTable2

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access from restricted IP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref RestrictedIP
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-EC2SecurityGroup
        - Key: Environment
          Value: !Ref Environment

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "AMI"]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref EC2SecurityGroup
          SubnetId: !Ref ACITWebSubnet1
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-EC2Instance
        - Key: Environment
          Value: !Ref Environment

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c94855ba95c71c99
    us-west-2:
      AMI: ami-0d6621c01e8c2de2c

Outputs:
  VPC:
    Description: The created VPC
    Value: !Ref VPC
  ACIT_Web_Subnet1:
    Description: ACIT_Web_Subnet1
    Value: !Ref ACITWebSubnet1
  ACIT_Web_Subnet2:
    Description: ACIT_Web_Subnet2
    Value: !Ref
