AWSTemplateFormatVersion: "2010-09-09"
Description: A template to create a VPC with structured ACIT subnet routing.

Parameters:
  Environment:
    Type: String
    Description: Environment name
    Default: acit-vpc-two
  VpcCIDR:
    Type: String
    Description: VPC CIDR block
    Default: 10.226.232.0/23
  ACITWebSubnet1CIDR:
    Type: String
    Description: CIDR block for ACIT_Web_Subnet1
    Default: 10.226.232.0/25
  ACITWebSubnet2CIDR:
    Type: String
    Description: CIDR block for ACIT_Web_Subnet2
    Default: 10.226.232.128/25
  ACITAPPSubnet1CIDR:
    Type: String
    Description: CIDR block for ACIT_APP_Subnet1
    Default: 10.226.233.0/25
  ACITAPPSubnet2CIDR:
    Type: String
    Description: CIDR block for ACIT_APP_Subnet2
    Default: 10.226.233.128/25
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair name for EC2 instance
  RestrictedIP:
    Type: String
    Description: Restricted IP for SSH access
    Default: 100.16.251.45/32

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      Tags:
        - Key: Name
          Value: !Sub ${Environment}
        - Key: Environment
          Value: !Ref Environment

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-IGW
        - Key: Environment
          Value: !Ref Environment

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  ACITWebSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ACITWebSubnet1CIDR
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ACIT_Web_Subnet2a
        - Key: Environment
          Value: !Ref Environment

  ACITWebSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ACITWebSubnet2CIDR
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ACIT_Web_Subnet2b
        - Key: Environment
          Value: !Ref Environment

  ACITAppSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ACITAPPSubnet1CIDR
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ACIT_APP_Subnet2a
        - Key: Environment
          Value: !Ref Environment

  ACITAppSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ACITAPPSubnet2CIDR
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: ACIT_APP_Subnet2b
        - Key: Environment
          Value: !Ref Environment

  NATIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway1:
    Type: AWS::EC2::NatGateway
    DependsOn: AttachGateway
    Properties:
      AllocationId: !GetAtt NATIP1.AllocationId
      SubnetId: !Ref ACITWebSubnet1

  NATIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway2:
    Type: AWS::EC2::NatGateway
    DependsOn: AttachGateway
    Properties:
      AllocationId: !GetAtt NATIP2.AllocationId
      SubnetId: !Ref ACITWebSubnet2

  ACITWebRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: ACIT_Web_RouteTable
        - Key: Environment
          Value: !Ref Environment

  ACITWebDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref ACITWebRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  ACITWebSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ACITWebSubnet1
      RouteTableId: !Ref ACITWebRouteTable

  ACITWebSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ACITWebSubnet2
      RouteTableId: !Ref ACITWebRouteTable

  ACITAppRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: ACIT_APP_RouteTable
        - Key: Environment
          Value: !Ref Environment

  ACITAppDefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ACITAppRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway1

  ACITAppSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ACITAppSubnet1
      RouteTableId: !Ref ACITAppRouteTable

  ACITAppSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ACITAppSubnet2
      RouteTableId: !Ref ACITAppRouteTable

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from restricted IP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref RestrictedIP
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-EC2SecurityGroup
        - Key: Environment
          Value: !Ref Environment

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "AMI"]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref EC2SecurityGroup
          SubnetId: !Ref ACITWebSubnet1
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-EC2Instance
        - Key: Environment
          Value: !Ref Environment

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c94855ba95c71c99
    us-west-2:
      AMI: ami-0d6621c01e8c2de2c

Outputs:
  VPC:
    Description: The created VPC
    Value: !Ref VPC
  ACITWebSubnet1:
    Description: ACIT_Web_Subnet2a
    Value: !Ref ACITWebSubnet1
  ACITWebSubnet2:
    Description: ACIT_Web_Subnet2b
    Value: !Ref ACITWebSubnet2
  ACITAPPSubnet1:
    Description: ACIT_APP_Subnet2a
    Value: !Ref ACITAppSubnet1
  ACITAPPSubnet2:
    Description: ACIT_APP_Subnet2b
    Value: !Ref ACITAppSubnet2
  EC2Instance:
    Description: The public EC2 instance
    Value: !Ref EC2Instance
  PublicIP:
    Description: The public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
  VPCId:
    Description: The ID of the created VPC
    Value: !Ref VPC
