AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create an EC2 instance with configurable VPC, Subnet, Security Group, Instance Type, AMI, Region, and User Data to install and start Apache HTTPD.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Choose the VPC where the instance will be deployed.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Choose the Subnet for the EC2 instance.
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Choose one or more Security Groups for the EC2 instance.
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
    Description: Choose the EC2 instance type.
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: Enter the AMI ID to use for this instance.
  Region:
    Type: String
    Description: Specify the region for the deployment (for reference only, not used in resources).
    Default: us-east-1

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      SubnetId: !Ref SubnetId
      SecurityGroupIds: !Ref SecurityGroupIds
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl enable httpd
          systemctl start httpd
          echo "<h1>ACIT Webserver 1 - Apache is running</h1>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: acit-webserver-1
        - Key: Env
          Value: DEV
        - Key: Purpose
          Value: Development

Outputs:
  InstanceId:
    Description: The Instance ID of the EC2 instance.
    Value: !Ref EC2Instance
  PublicIp:
    Description: The public IP address of the EC2 instance.
    Value: !GetAtt EC2Instance.PublicIp
  PrivateIp:
    Description: The private IP address of the EC2 instance.
    Value: !GetAtt EC2Instance.PrivateIp
